### ISSUE TITLE
getr command not working in Python2

### ISSUE THREAD

**Issue by fredrikhr** [PMunch/mpfshell#4]
When executing the `getr` command with a directory name that exists and contains files, the `getr` fails fatally.

```
>mpfshell

[32m** Micropython File Shell v0.7.6, sw@kaltpost.de ** [39m
-- Running on Python 2.7 using PySerial 3.2.1 --

mpfs [/]> open ...
Connected to LoPy
mpfs [/]> ls

Remote files in '/':

 <dir> flash

mpfs [/]> getr flash
global name 'FileNotFoundError' is not defined
``` 
Environment:
```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
```

**Comment by PMunch** [comment]
FileNotFoundError was introduced in Python 3, you're using Python 2. The original mpfshell is made to support both Python 2 and Python 3. This version has only been tested with Python 3. Whether or not legacy Python should be supported is open for questioning, but certainly not a priority.
